//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmlogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public string DVT { get; set; }
        public string DG { get; set; }
        public Nullable<int> MALOAISP { get; set; }
        public byte[] HINHANH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
    }
}
